In [2]:
import pandas as pd

In [3]:
def parse(game_log_file, touch_log_file, label):
    game_logs = pd.read_csv(game_log_file)
    touch_logs = pd.read_csv(touch_log_file)
    pass

In [4]:
GAME_LOG_HEADER = ['Time',
                   'Event',
                   'X-coord',
                   'Y-coord']
TOUCH_LOG_HEADER = ['Timestamp-sec',
                    'Timestamp-ms', 
                    'touch-event',
                    'X-coord',
                    'Y-coord',
                    'Contact-major',
                    'Contact-minor']

## Bot logs

In [9]:
bot_game_logs = pd.read_csv('logs/bot_game_logs_1.csv',
                        names=GAME_LOG_HEADER,
                        header=None,
                        index_col=False)
bot_touch_logs = pd.read_csv('logs/bot_touch_logs_1.csv',
                         header=None,
                         names=TOUCH_LOG_HEADER,
                         index_col=False)

In [17]:
bot_game_logs.describe()

                Time      X-coord     Y-coord
count     314.000000   314.000000  194.000000
mean   227431.531847   784.626402  566.849169
std    123539.602489   561.648682  204.803991
min        43.000000     1.000000    8.009033
25%    127401.250000   222.500000  475.243850
50%    229435.000000   786.430675  584.511120
75%    324613.750000  1242.703350  696.489255
max    463252.000000  2011.875000  994.998800

In [22]:
bot_game_logs

       Time   Event     X-coord    Y-coord
0        43   Touch  1831.93360  801.00220
1     13766   Touch  1165.96070  302.99194
2     17919   Touch  1360.94240  460.99730
3     21485   Touch  1220.90520  548.99780
4     21504   Fight    10.00000        NaN
5     24622   Touch  1433.90810  643.98560
6     25147   Touch  1383.90930  625.00120
7     25671   Touch  1332.89430  604.00635
8     26134   Fight    20.00000        NaN
9     28782   Touch   841.91710  783.99536
10    29430   Fight    30.00000        NaN
11    31375   Touch   911.96960  680.00977
12    32021    Drop     1.00000        NaN
13    34152   Touch   643.95447  710.99120
14    36993   Touch   853.90870  677.99927
15    37492   Fight    40.00000        NaN
16    37522   Touch   906.95620  636.99830
17    38051   Touch   959.93590  595.00854
18    41445   Touch  1493.93370  458.98682
19    41969   Touch  1433.90810  465.01830
20    42206    Drop     2.00000        NaN
21    42930   Fight    50.00000        NaN
22    45949   Touch  1628.88980  249.99390
23    47133   Fight    60.00000        NaN
24    47909   Fight    70.00000        NaN
25    53686   Touch  1634.91940  181.01074
26    54219   Touch  1554.90780  227.02148
27    54744   Touch  1477.94500  272.99927
28    58983   Touch  1198.95450  555.98510
29    59107   Fight    80.00000        NaN
..      ...     ...         ...        ...
284  409978   Fight   610.00000        NaN
285  410368   Touch   830.94180  772.98706
286  413605   Touch  1109.93230  613.00415
287  413849   Fight   620.00000        NaN
288  417283   Touch  1819.94200  814.97680
289  418432    Drop    50.00000        NaN
290  418713   Fight   630.00000        NaN
291  420984   Touch  1713.91480  701.00464
292  421508   Touch  1568.93190  654.99390
293  422031   Touch  1422.93270  607.00560
294  422463    Drop    51.00000        NaN
295  422463   Fight   640.00000        NaN
296  422555   Touch  1276.93360  561.98364
297  422741   Fight   650.00000        NaN
298  428225   Touch  1216.90800  498.01025
299  428396    Drop    52.00000        NaN
300  428790    Drop    53.00000        NaN
301  431606   Touch  1292.92240  445.01220
302  437558   Touch  1415.95460  354.01245
303  437991    Drop    54.00000        NaN
304  443440   Touch   936.96900  649.98413
305  449037   Touch  1064.94690  619.99146
306  449037    Drop    55.00000        NaN
307  455088   Touch  1637.90040  994.99880
308  455621   Touch  1558.90500  923.97217
309  456149   Touch  1479.90970  854.00024
310  456672   Touch  1399.89810  783.99536
311  462544   Touch  1642.91380  990.97780
312  462725   Touch  1637.90040  994.99880
313  463252   Touch  1558.90500  923.97217

[314 rows x 4 columns]

In [18]:
bot_touch_logs.describe()

,Timestamp-sec,Timestamp-ms,touch-event,X-coord,Y-coord,Contact-major,Contact-minor
count,3.940000e+02,394.000000,394.000000,394.000000,394.000000,394.000000,394.000000
mean,1.548375e+09,487.000000,0.997462,1158.916280,573.537145,13.717632,13.717632
std,1.284624e+02,283.515221,0.992334,364.461787,209.780543,2.860890,2.860890
min,1.548375e+09,1.000000,0.000000,30.961304,8.009033,8.761597,8.761597
25%,1.548375e+09,244.250000,0.000000,850.927730,481.992200,11.241531,11.241531
50%,1.548375e+09,471.500000,1.000000,1190.960100,595.008540,13.721466,13.721466
75%,1.548375e+09,730.250000,2.000000,1431.943400,701.993400,16.201401,16.201401
max,1.548375e+09,995.000000,2.000000,2011.875000,994.998800,18.479920,18.479920

In [23]:
bot_touch_logs

,Timestamp-sec,Timestamp-ms,touch-event,X-coord,Y-coord,Contact-major,Contact-minor
0,1548374563,802,0.0,1831.93360,801.00220,8.761597,8.761597
1,1548374577,119,2.0,1165.96070,302.99194,8.811951,8.811951
2,1548374577,525,0.0,1165.96070,302.99194,8.811951,8.811951
3,1548374581,667,2.0,1360.94240,460.99730,8.862305,8.862305
4,1548374581,678,0.0,1360.94240,460.99730,8.862305,8.862305
5,1548374585,234,2.0,1220.90520,548.99780,8.912659,8.912659
6,1548374585,244,0.0,1220.90520,548.99780,8.912659,8.912659
7,1548374588,369,2.0,1433.90810,643.98560,8.963013,8.963013
8,1548374588,381,0.0,1433.90810,643.98560,8.963013,8.963013
9,1548374588,895,2.0,1383.90930,625.00120,9.013367,9.013367
10,1548374588,906,0.0,1383.90930,625.00120,9.013367,9.013367
11,1548374589,422,2.0,1332.89430,604.00635,9.063721,9.063721
12,1548374589,430,0.0,1332.89430,604.00635,9.063721,9.063721
13,1548374592,529,2.0,841.91710,783.99536,9.114075,9.114075
14,1548374592,541,0.0,841.91710,783.99536,9.114075,9.114075
15,1548374595,123,2.0,911.96960,680.00977,9.164429,9.164429
16,1548374595,134,0.0,911.96960,680.00977,9.164429,9.164429
17,1548374597,901,2.0,643.95447,710.99120,9.214783,9.214783
18,1548374597,911,0.0,643.95447,710.99120,9.214783,9.214783
19,1548374600,743,2.0,853.90870,677.99927,9.265137,9.265137
20,1548374600,752,0.0,853.90870,677.99927,9.265137,9.265137
21,1548374601,267,2.0,906.95620,636.99830,9.315491,9.315491
22,1548374601,281,0.0,906.95620,636.99830,9.315491,9.315491
23,1548374601,797,2.0,959.93590,595.00854,9.365845,9.365845
24,1548374601,810,0.0,959.93590,595.00854,9.365845,9.365845
25,1548374605,194,2.0,1493.93370,458.98682,9.416199,9.416199
26,1548374605,204,0.0,1493.93370,458.98682,9.416199,9.416199
27,1548374605,718,2.0,1433.90810,465.01830,9.466553,9.466553
28,1548374605,728,0.0,1433.90810,465.01830,9.466553,9.466553
29,1548374609,697,2.0,1628.88980,249.99390,9.516907,9.516907
...,...,...,...,...,...,...,...
364,1548374991,984,0.0,1216.90800,498.01025,17.926025,17.926025
365,1548374995,355,2.0,1292.92240,445.01220,17.976380,17.976380
366,1548374995,365,0.0,1292.92240,445.01220,17.976380,17.976380
367,1548375001,308,2.0,1415.95460,354.01245,18.026733,18.026733
368,1548375001,317,0.0,1415.95460,354.01245,18.026733,18.026733
369,1548375007,187,2.0,936.96900,649.98413,18.077087,18.077087
370,1548375007,199,0.0,936.96900,649.98413,18.077087,18.077087
371,1548375012,790,2.0,1064.94690,619.99146,18.127441,18.127441
372,1548375012,796,0.0,1064.94690,619.99146,18.127441,18.127441
373,1548375018,830,2.0,1637.90040,994.99880,18.177795,18.177795
374,1548375018,847,0.0,1637.90040,994.99880,18.177795,18.177795
375,1548375019,368,2.0,1558.90500,923.97217,18.228150,18.228150
376,1548375019,380,0.0,1558.90500,923.97217,18.228150,18.228150
377,1548375019,897,2.0,1479.90970,854.00024,18.278503,18.278503
378,1548375019,908,0.0,1479.90970,854.00024,18.278503,18.278503
379,1548375020,420,2.0,1399.89810,783.99536,18.328857,18.328857
380,1548375020,431,0.0,1399.89810,783.99536,18.328857,18.328857
381,1548375026,181,2.0,1704.90420,955.97534,18.379211,18.379211
382,1548375026,201,1.0,1685.46020,966.98364,18.379211,18.379211
383,1548375026,219,1.0,1672.21300,975.38275,18.379211,18.379211
384,1548375026,239,1.0,1663.46080,978.98070,18.379211,18.379211
385,1548375026,252,1.0,1656.06910,983.84705,18.379211,18.379211
386,1548375026,270,1.0,1650.65870,986.00100,18.379211,18.379211
387,1548375026,287,1.0,1646.80160,989.98900,18.379211,18.379211
388,1548375026,303,1.0,1642.91380,990.97780,18.379211,18.379211
389,1548375026,303,0.0,1642.91380,990.97780,18.379211,18.379211
390,1548375026,468,2.0,1637.90040,994.99880,18.429565,18.429565
391,1548375026,484,0.0,1637.90040,994.99880,18.429565,18.429565
392,1548375027,3,2.0,1558.90500,923.97217,18.479920,18.479920
393,1548375027,11,0.0,1558.90500,923.97217,18.479920,18.479920

In [84]:
b_touch_test = bot_touch_logs.copy()
b_game_test = bot_game_logs.copy()

first_touch_row = b_touch_test[:1]
first_game_row = b_game_test[:1]

start_time = first_touch_row['Timestamp-sec'] + first_touch_row['Timestamp-ms']/1000 - first_game_row['Time']/1000
start_time[0]

1548374563.759

In [85]:
b_touch_test['Time'] = b_touch_test['Timestamp-sec'] + b_touch_test['Timestamp-ms']/1000 - start_time[0]
b_touch_test = b_touch_test.drop(b_touch_test.columns[[0, 1, 5, 6]], axis=1)

In [86]:
b_touch_test['Time'] = round(b_touch_test['Time'] * 1000).apply(int)

In [87]:
b_touch_test

     touch-event     X-coord    Y-coord    Time
0            0.0  1831.93360  801.00220      43
1            2.0  1165.96070  302.99194   13360
2            0.0  1165.96070  302.99194   13766
3            2.0  1360.94240  460.99730   17908
4            0.0  1360.94240  460.99730   17919
5            2.0  1220.90520  548.99780   21475
6            0.0  1220.90520  548.99780   21485
7            2.0  1433.90810  643.98560   24610
8            0.0  1433.90810  643.98560   24622
9            2.0  1383.90930  625.00120   25136
10           0.0  1383.90930  625.00120   25147
11           2.0  1332.89430  604.00635   25663
12           0.0  1332.89430  604.00635   25671
13           2.0   841.91710  783.99536   28770
14           0.0   841.91710  783.99536   28782
15           2.0   911.96960  680.00977   31364
16           0.0   911.96960  680.00977   31375
17           2.0   643.95447  710.99120   34142
18           0.0   643.95447  710.99120   34152
19           2.0   853.90870  677.99927   36984
20           0.0   853.90870  677.99927   36993
21           2.0   906.95620  636.99830   37508
22           0.0   906.95620  636.99830   37522
23           2.0   959.93590  595.00854   38038
24           0.0   959.93590  595.00854   38051
25           2.0  1493.93370  458.98682   41435
26           0.0  1493.93370  458.98682   41445
27           2.0  1433.90810  465.01830   41959
28           0.0  1433.90810  465.01830   41969
29           2.0  1628.88980  249.99390   45938
..           ...         ...        ...     ...
364          0.0  1216.90800  498.01025  428225
365          2.0  1292.92240  445.01220  431596
366          0.0  1292.92240  445.01220  431606
367          2.0  1415.95460  354.01245  437549
368          0.0  1415.95460  354.01245  437558
369          2.0   936.96900  649.98413  443428
370          0.0   936.96900  649.98413  443440
371          2.0  1064.94690  619.99146  449031
372          0.0  1064.94690  619.99146  449037
373          2.0  1637.90040  994.99880  455071
374          0.0  1637.90040  994.99880  455088
375          2.0  1558.90500  923.97217  455609
376          0.0  1558.90500  923.97217  455621
377          2.0  1479.90970  854.00024  456138
378          0.0  1479.90970  854.00024  456149
379          2.0  1399.89810  783.99536  456661
380          0.0  1399.89810  783.99536  456672
381          2.0  1704.90420  955.97534  462422
382          1.0  1685.46020  966.98364  462442
383          1.0  1672.21300  975.38275  462460
384          1.0  1663.46080  978.98070  462480
385          1.0  1656.06910  983.84705  462493
386          1.0  1650.65870  986.00100  462511
387          1.0  1646.80160  989.98900  462528
388          1.0  1642.91380  990.97780  462544
389          0.0  1642.91380  990.97780  462544
390          2.0  1637.90040  994.99880  462709
391          0.0  1637.90040  994.99880  462725
392          2.0  1558.90500  923.97217  463244
393          0.0  1558.90500  923.97217  463252

[394 rows x 4 columns]

In [35]:
first_touch_row

,Timestamp-sec,Timestamp-ms,touch-event,X-coord,Y-coord,Contact-major,Contact-minor
0,1548374563,802,0.0,1831.9336,801.0022,8.761597,8.761597

In [36]:
first_game_row

   Time   Event    X-coord   Y-coord
0    43   Touch  1831.9336  801.0022

## Human logs

In [12]:
human_game_logs = pd.read_csv('logs/human_game_logs_1.csv',
                        names=GAME_LOG_HEADER,
                        header=None,
                        index_col=False)
human_touch_logs = pd.read_csv('logs/human_touch_logs_1.csv',
                         header=None,
                         names=TOUCH_LOG_HEADER,
                         index_col=False)

In [15]:
human_game_logs.describe()

                Time      X-coord      Y-coord
count     503.000000   503.000000   229.000000
mean   156450.017893   724.552330   535.443119
std     92768.515837   567.142974   232.192792
min         3.000000     1.000000   163.015140
25%     73350.500000   115.500000   322.009280
50%    153688.000000   682.977900   525.003660
75%    239502.500000  1188.481450   754.002700
max    313612.000000  2099.880900  1080.477900

In [16]:
human_touch_logs.describe()

,Timestamp-sec,Timestamp-ms,touch-event,X-coord,Y-coord,Contact-major,Contact-minor
count,1.492000e+03,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000
mean,1.548375e+09,483.279491,0.999330,1080.485152,539.209764,24.741028,24.741028
std,9.222993e+01,283.700637,0.553629,440.658710,231.982234,3.250556,3.250556
min,1.548375e+09,0.000000,0.000000,217.948610,158.005370,18.580627,18.580627
25%,1.548375e+09,251.750000,1.000000,708.434588,316.999500,21.903992,21.903992
50%,1.548375e+09,452.000000,1.000000,1065.717700,525.992430,24.723816,24.723816
75%,1.548376e+09,751.000000,1.000000,1496.152475,754.002700,27.644348,27.644348
max,1.548376e+09,999.000000,2.000000,2099.880900,1080.477900,30.061340,30.061340